name: Analyse

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              with:
                version: 9

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2

            - name: Init
              run: make init
              shell: bash

            - name: Run tests
              run: bun test

    biome:
        name: Biome
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Biome
              uses: biomejs/setup-biome@v2
              with:
                version: latest

            - name: Run Biome
              run: biome ci .
